company_profile/cp_admin/ckeditor_uploader/urls.py
from __future__ import absolute_import

from django.urls import re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

from django.urls import reverse
from ckeditor_uploader import views

urlpatterns = [
    re_path(r'^upload/', login_required(views.upload, login_url='/cms/login/'), name='ckeditor_upload'),
    re_path(r'^browse/', never_cache(login_required(views.browse, login_url='/cms/login/')), name='ckeditor_browse'),
]

company_profile/cp_admin/urls.py
from django.urls import path, re_path
from .views import Activation, Register, Login, Index, CmsArticle, Logout, CmsPage, CmsCategory, CmsAsset, CmsIdentity, CmsTemplate, CmsColor, CmsComment, CmsReply

app_name = 'cms'

urlpatterns = [
    path('article/<str:action>/<int:pk>/', CmsArticle.as_view(), name='article_edit_delete'),
    path('article/<str:action>/', CmsArticle.as_view(), name='article_add'),
    path('article/', CmsArticle.as_view(), name='article_all'),

    path('category/<str:action>/<int:pk>/', CmsCategory.as_view(), name='category_edit_delete'),
    path('category/<str:action>/', CmsCategory.as_view(), name='category_add'),
    path('category/', CmsCategory.as_view(), name='category_all'),

    path('page/<str:action>/<int:pk>/', CmsPage.as_view(), name='page_edit_delete'),
    path('page/<str:action>/', CmsPage.as_view(), name='page_add'),
    path('page/', CmsPage.as_view(), name='page_all'),

    path('asset/<str:action>/<int:pk>/', CmsAsset.as_view(), name='asset_edit'),
    path('asset/', CmsAsset.as_view(), name='asset_all'),

    path('identity/<str:action>/<int:pk>/', CmsIdentity.as_view(), name='identity_edit'),
    path('identity/', CmsIdentity.as_view(), name='identity_all'),

    path('template/<str:action>/<int:pk>/', CmsTemplate.as_view(), name='template_edit'),
    path('template/', CmsTemplate.as_view(), name='template_all'),

    path('color/<str:action>/<int:pk>/', CmsColor.as_view(), name='color_edit'),

    path('comment/add/<slug:article_slug>/', CmsComment.as_view(), name='comment_add'),
    path('comment/<str:action>/<int:pk>/', CmsComment.as_view(), name='comment_edit_approve_delete'),
    path('comment/', CmsComment.as_view(), name='comment_all'),
    
    path('reply/<str:action>/<int:pk>/', CmsReply.as_view(), name='reply_add'),
    path('reply/<str:action>/<int:pk>/', CmsReply.as_view(), name='reply_edit_approve_delete'),

    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('activation/', Activation.as_view(), name='activation'),
    path('register/<str:key>/', Register.as_view(), name='register'),
    path('', Index.as_view(), name='index'),
]

zeon_backend/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dispatcher.views import Index, Blog, Article, Page, Comment, ArticleList, Reply
from django.conf import settings
from django.conf.urls.static import static
from company_profile.cp_admin import urls as cp_admin
from store.st_admin import urls as st_admin

import company_profile.cp_admin.ckeditor_uploader.urls as ckeditor_uploader_urls
import store.st_storefront.urls as storefront
import store.st_database_wilayah.urls as wilayah
import store.st_shopping_cart.urls as cart
import store.st_purchase_order.urls as order
#import shipping_backend.urls as shipping

from store.st_purchase_order.views import checkout, pay, history

urlpatterns = [
    path('wilayah/', include(wilayah, namespace='wilayah_backend')),
    path('cart/', include(cart, namespace='cart_backend')),
    path('checkout/', checkout, name="checkout"),
    path('pay/', pay, name="pay"),
    path('history/', history, name="history"),
    path('order/', include(order, namespace='order_backend')),
    #path('shipping/', include(shipping, namespace='shipping_backend')),
    path('str/', include(st_admin, namespace='st_admin')),
    path('cms/', include(cp_admin, namespace='cp_admin')),
    path('core/admin/', admin.site.urls),
    path('blog/<str:kategori>/<str:slug>/', Article.as_view(), name="blog_detail"),
    path('comment/<str:article_slug>/<str:method>/', Comment.as_view(), name="add_comment"),
    path('comment/<str:article_slug>/', Comment.as_view(), name="view_all_comment"),
    path('reply/<str:article_slug>/<int:comment_pk>/<str:method>/', Reply.as_view(), name="add_reply"),
    re_path(r'^$', Index.as_view()), 
    re_path(r'^blog/$', Blog.as_view(), name="blog_index"),
    re_path(r'^ckeditor/', include(ckeditor_uploader_urls)),
    re_path(r'^store/', include(storefront, namespace='store_backend')),
    re_path(r'^taggit/', include('taggit_selectize.urls')),
    path('<str:page_slug>/', Page.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company_profile/cp_admin/forms.py
from django import forms
from django.contrib.auth.models import User
from membership.models import Member
from company_profile.cp_user_configs.forms import AssetEditForm, IdentityEditForm

class CmsLoginForm(forms.Form):
    username = forms.CharField(label='Username:', max_length=150)
    attrs = {
        "type": "password"
    }
    password = forms.CharField(label='Password :', widget=forms.PasswordInput(attrs=attrs))


class CmsActivationForm(forms.Form):
    user_id = forms.CharField(widget = forms.HiddenInput(), max_length=150)
    access_key = forms.CharField(widget = forms.HiddenInput())

class CmsRegisterForm(forms.Form):
    user_id = forms.CharField(widget = forms.HiddenInput(), max_length=150)
    access_key = forms.CharField(widget = forms.HiddenInput())
    username = forms.CharField(label='Username:', max_length=150)
    attrs = {
        "type": "password"
    }
    password = forms.CharField(label='Password :', widget=forms.PasswordInput(attrs=attrs))
    site_domain = forms.CharField(label='Site Domain:', max_length=150)

    def __init__(self, *args, **kwargs):
        super(CmsRegisterForm, self).__init__(*args, **kwargs)
        self.fields['site_domain'].widget.attrs['style'] = 'width:50%; padding:10px; display:inline-block'

class CmsBrandAssetsForm(AssetEditForm):
    def __init__(self, *args, **kwargs):
            super(CmsBrandAssetsForm, self).__init__(*args, **kwargs)
            
class CmsBrandIdentityForm(IdentityEditForm):
    def __init__(self, *args, **kwargs):
            super(CmsBrandIdentityForm, self).__init__(*args, **kwargs)

company_profile/cp_admin/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.models import Site
from django.http import HttpResponseRedirect, HttpResponseForbidden, JsonResponse, HttpResponse
from django.middleware.csrf import get_token
from django.shortcuts import render
from django.urls import reverse
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string

import time
from dispatcher.views import Dispatcher
from company_profile.cp_user_configs.models import UserConfigs, UserFormTemplate
from company_profile.cp_articles.models import Article as ArticleModel
from company_profile.cp_articles.models import Category as CategoryModel
from company_profile.cp_pages.models import PageModel
from company_profile.cp_configs.models import Template, ColorScheme, BrandAsset, BrandIdentity

from company_profile.cp_articles.views import CPArticle, CPCategory
from company_profile.cp_pages.views import CPPage
from company_profile.cp_user_configs.views import CPAsset, CPIdentity, CPTemplate, CPColor
from company_profile.cp_comment.views import CPComment, CPReply
from company_profile.cp_comment.models import Comment, Reply, Visitor

from membership.models import Member, PackageGroup


from .forms import CmsLoginForm, CmsActivationForm, CmsRegisterForm

class Logout(Dispatcher):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('cms:login'))
    def post(self, request, *args, **kwargs):
        pass

class Activation(Dispatcher):
    template = "cp_admin/index.html"
    form = CmsActivationForm()
    def get(self, request, *args, **kwargs):
        user_id = request.GET.get('id', '')
        access_key = request.GET.get('access_key', '')


        if Member.objects.filter(activation_code=access_key).exists():
            member_object = Member.objects.filter(activation_code=access_key)[0]
            return HttpResponseRedirect('%s://%s:8000%s'%(request.scheme, member_object.site.domain, reverse('cms:login')))


        if user_id and access_key:
            self.form = CmsActivationForm(initial={'user_id': user_id, 'access_key':access_key})
        code = request.GET.get('code', 200)
        token = get_token(request)
        data = super(Activation, self).get(request, args, kwargs)
        configs = UserConfigs.objects.get(member = data['member'])
        self.component['base']='cp_admin/component/activation_base.html'
        self.component['header']='cp_admin/component/activation_header.html'
        self.component['main']='cp_admin/component/activation_main.html'
        self.component['local_script']='cp_admin/component/activation_local_script.html'
        return render(request, self.template, {
                'component': self.component,
                'form' : self.form,
                'token' : token,
                'code' : code
            }
        )
    def post(self, request, *args, **kwargs):
        token = get_token(request)
        self.form = CmsActivationForm(request.POST)
        if self.form.is_valid():
            data = super(Activation, self).get(request, args, kwargs)
            post_data = self.form.cleaned_data
            user_id = post_data.get('user_id')
            access_key = post_data.get('access_key')
            if Member.objects.filter(activation_code=access_key).exists():
                member_object = Member.objects.filter(activation_code=access_key)[0]
                return JsonResponse({'new_token': get_token(request), 
                    'redirect_url':'%s://%s%s'%(request.scheme, member_object.site.domain, reverse('cms:login'))}, status=200)

            random_string = get_random_string(10, allowed_chars='1234567890SIDOMO')
            while User.objects.filter(username = random_string).exists():
               random_string = get_random_string(10, allowed_chars='12345677890SIDOMO')

            user = User.objects.create(username=random_string, 
                password=get_random_string(10, allowed_chars='1234567890SIDOMO'),
                )
            if user:
                member = Member.objects.create(user=user, 
                sidomo_user_id = user_id,
                activation_code=access_key)
                member.package_group.add(PackageGroup.objects.get(name='web-member'))
                member.save()

            if request.user.is_authenticated:
                return JsonResponse({'new_token': get_token(request), 
                    'redirect_url':'%s://%s%s'%(request.scheme, member_object.site.domain, reverse('cms:index'))}, status=200)


            return JsonResponse({'new_token': get_token(request), 
                'redirect_url':reverse('cms:register', kwargs={'key':access_key})}, status=200)
        
        self.component['base']='cp_admin/component/activation_base.html'
        self.component['header']='cp_admin/component/activation_header.html'
        self.component['main']='cp_admin/component/activation_main.html'
        self.component['local_script']='cp_admin/component/activation_local_script.html'
        return render(request, self.template, {
                'component': self.component,
                'form' : self.form,
                'token' : token,
            }
        )

class Register(Dispatcher):
    template = "cp_admin/index.html"
    form = CmsRegisterForm()
    def get(self, request, *args, **kwargs):
        access_key = kwargs['key']
        if access_key:
            member = Member.objects.get(activation_code=access_key)
            if not member:
                return HttpResponseRedirect(reverse('cms:activation'))
            self.form = CmsRegisterForm(initial={'user_id': member.sidomo_user_id, 
                'site_domain': 'username',
                'access_key':access_key})
        else :
            return HttpResponseRedirect(reverse('cms:activation'))
        code = request.GET.get('code', 200)
        token = get_token(request)
        data = super(Register, self).get(request, args, kwargs)
        configs = UserConfigs.objects.get(member = data['member'])
        self.component['base']='cp_admin/component/register_base.html'
        self.component['header']='cp_admin/component/register_header.html'
        self.component['main']='cp_admin/component/register_main.html'
        self.component['local_script']='cp_admin/component/register_local_script.html'
        return render(request, self.template, {
                'component': self.component,
                'form' : self.form,
                'token' : token,
                'code' : code
            }
        )
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return  HttpResponse(status=403)
        access_key = kwargs['key']
        if access_key:
            member = Member.objects.get(activation_code=access_key)
            if not member:
                return HttpResponseRedirect(reverse('cms:activation'))
        else :
            return  HttpResponse(status=404)

        token = get_token(request)
        self.form = CmsRegisterForm(request.POST)
        if self.form.is_valid():
            data = super(Register, self).get(request, args, kwargs)
            post_data = self.form.cleaned_data
            submitted_user_id = post_data.get('user_id')
            submitted_access_key = post_data.get('access_key')
            submitted_username = post_data.get('username')
            submitted_password = post_data.get('password')
            submitted_site_domain = post_data.get('site_domain').lower()+'.sidomo.com' 

            is_exist = User.objects.filter(username=submitted_username).exists()
            is_domain_used = Site.objects.filter(domain=submitted_site_domain).exists()
            if (not submitted_access_key == access_key) or\
                (not submitted_access_key == member.activation_code) or\
                (not access_key == member.activation_code) or\
                (not submitted_user_id == member.sidomo_user_id) or (is_exist == True) or (is_domain_used == True) :
                return  HttpResponse(status=404)

            user = member.user
            user.username = submitted_username
            user.set_password(submitted_password)
            user.save()

            site = Site.objects.create(domain=submitted_site_domain,
                    name=submitted_site_domain)
            member.site = site 
            member.save()

            configs = UserConfigs.objects.create(member = member)
            configs.templates = Template.objects.get(name = 'default')
            configs.color_scheme = ColorScheme.objects.get(name = 'default')
            configs.brand_assets = BrandAsset.objects.get(name = 'default')
            configs.brand_identity = BrandIdentity.objects.get(name = 'default')
            configs.save()

            form_template = UserFormTemplate.objects.create(member=member)

            return JsonResponse({'new_token': get_token(request),
                'domain':site.domain, 
                'redirect_url':'http://%s:8000%s?u=%s&p=%s'%(site.domain, 
                    reverse('cms:login'),
                    user.username,
                    submitted_password,
                    )}, status=200)
        else:    
            fields = [f for f in self.form]
            return HttpResponse(['%s; '%e.errors for e in fields],status=400)
        
        self.component['base']='cp_admin/component/register_base.html'
        self.component['header']='cp_admin/component/register_header.html'
        self.component['main']='cp_admin/component/register_main.html'
        self.component['local_script']='cp_admin/component/register_local_script.html'
        return render(request, self.template, {
                'component': self.component,
                'form' : self.form,
                'token' : token,
            }

company_profile/cp_admin/templates/cp_admin/component/activation_base.html
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="/static/assets/images/favicon.png">
    <title>Xtreme admin Template - The Ultimate Multipurpose admin template</title>
    <!-- chartist CSS -->
    <link href="/static/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="/static/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.css" rel="stylesheet">
    <!--c3 CSS -->
    <link href="/static/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/static/dist/css/style.min.css" rel="stylesheet">
    <style>
        @-webkit-keyframes rotating /* Safari and Chrome */ {
            from {
            -webkit-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
            }
            to {
            -webkit-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
            }
            }
        @keyframes rotating {
            from {
            -ms-transform: rotate(0deg);
            -moz-transform: rotate(0deg);
            -webkit-transform: rotate(0deg);
            -o-transform: rotate(0deg);
            transform: rotate(0deg);
            }
            to {
            -ms-transform: rotate(360deg);
            -moz-transform: rotate(360deg);
            -webkit-transform: rotate(360deg);
            -o-transform: rotate(360deg);
            transform: rotate(360deg);
            }
        }
        .rotating {
            -webkit-animation: rotating 3s linear infinite;
            -moz-animation: rotating 3s linear infinite;
            -ms-animation: rotating 3s linear infinite;
            -o-animation: rotating 3s linear infinite;
            animation: rotating 3s linear infinite;
        }
        .hidden{
            display: none;
        }
        .show{
            display: block; 
            display: flex; 
            justify-content: center; 
        }
        .danger{
            color: #ff5555
        }
        .success{
            color: #137413
        }
        input{
            padding: 13px 6px;
            margin: 6px 0;
            width: 100%
        }
    </style>
</head>

<body style="background: #109800">
    {% block header %}
    {% endblock header %}
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
    {% block main_wrapper %}
    {% endblock main_wrapper %}
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- customizer Panel -->
    <!-- ============================================================== -->
    <script src="/static/assets/libs/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="/static/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="/static/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <script>
        function getNext(url, token){
            $.get(url,
            {
                method:'get_component',
            },
                //or your custom data either as object {foo: "bar", ...} or foo=bar&...
                function (data, status){    
                    var stateObj = { obj: url };
                    history.pushState(stateObj, url, url);
                    if(status=='success'){    
                        $('#main-wrapper').html(data['main']);
                        $('#local_script').html(data['local_script']);
                    }
                },
            ).fail(function(xhr) {
                alert(xhr.status);
                if(xhr.status == 403){
                    window.open(url+"?code=403", "_self");
                }else if(xhr.status == 404){
                    window.open(url+"?code=404", "_self");
                }else if(xhr.status == 500){
                    window.open(url+"?code=500", "_self");
                }
            });
        }
    </script>
    <div id='local_script'>
        {% block local_script %}{% endblock local_script %}
    </div>
</body>

</html>

company_profile/cp_admin/templates/cp_admin/component/cms_article_delete_local_script.html
<script>
    function localScript(){
        var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
        for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '1') {
                t.setAttribute('data-processed', '0');
            }
        }
        function initialiseCKEditor() {
            var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
            for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '0' && t.id.indexOf('__prefix__') == -1) {
                t.setAttribute('data-processed', '1');
                var ext = JSON.parse(t.getAttribute('data-external-plugin-resources'));
                for (var j=0; j<ext.length; ++j) {
                CKEDITOR.plugins.addExternal(ext[j][0], ext[j][1], ext[j][2]);
                }
                CKEDITOR.replace(t.id, JSON.parse(t.getAttribute('data-config')));
            }
            }
        }
        
        function initialiseCKEditorInInlinedForms() {
            document.body.addEventListener('click', function(e) {
            if (e.target && (
                e.target.matches('.add-row a') ||
                e.target.matches('.grp-add-handler')
            )) {
                initialiseCKEditor();
            }
            });
        }
        
        setTimeout(initialiseCKEditor(), 4000);
        
        setTimeout(initialiseCKEditorInInlinedForms(), 4000);
    }

    
</script>

company_profile/cp_admin/templates/cp_admin/component/index_local_script.html
<script>
    function testScript(){
        alert("OK");
    }
</script>

company_profile/cp_admin/templates/cp_admin/component/login_header.html
<header class="topbar" style="background: #109800">
    <div class="navbar top-navbar navbar-expand-md" style="display: flex; justify-content: center">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <b class="logo-icon">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="/static/images/PNG-robot -copy.png" width="40px" height="auto"/>
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                     <h5 style="color:#fff">SIDOMO CMS</h5>
                </span>
            </a>
        </div>
    </div>
</header>

company_profile/cp_admin/templates/cp_admin/component/login_local_script.html
<script>
    function formLogin(){
    var username = $("#id_username").val();
    var password = $("#id_password").val();
    $('#formTitle').html('<h2>Mencoba masuk sebagai <br>' + username + "</h2>");
    $('#formContainer').html('');
    $('#gearContainer').removeClass('hidden');
    $('#gearContainer').addClass('show');
    $.post($("loginForm").attr("action"),
        {
            csrfmiddlewaretoken:"{{token}}",
            username:username,
            password:password,
        },
            //or your custom data either as object {foo: "bar", ...} or foo=bar&...
            function (data, status){    
                if(status=='success'){    
                    $('#formTitle').html('<h1 class="success">Login Berhasil</h1>');
                    $('#gearContainer').removeClass('show');
                    $('#gearContainer').addClass('hidden');
                    $('#formContainer').html("<p style='margin: 50px 0; width:100%; text-align:center'>Anda akan diarahkan ke dashboard</p>");
                    setTimeout(function(){
                       window.open(data['redirect_url'], '_self');
                    }, 5000);
                }
                },
        ).fail(function(xhr) {
            if(xhr.status == 403){
                window.open("{% url 'cms:login' %}?code=403", "_self");
            }else if(xhr.status == 404){
                window.open("{% url 'cms:login' %}?code=404", "_self");
            }else if(xhr.status == 500){
                window.open("{% url 'cms:login' %}?code=500", "_self");
            }
        });
    }
</script>

company_profile/cp_admin/templates/cp_admin/component/register_header.html
<header class="topbar" style="background: #109800">
    <div class="navbar top-navbar navbar-expand-md" style="display: flex; justify-content: center">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <b class="logo-icon">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="/static/images/PNG-robot -copy.png" width="40px" height="auto"/>
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                     <h5 style="color:#fff">SIDOMO CMS</h5>
                </span>
            </a>
        </div>
    </div>
</header>

company_profile/cp_admin/templates/cp_admin/component/register_local_script.html
<script>
    function formLogin(){
    var user_id = $("#id_user_id").val();
    var access_key = $("#id_access_key").val();
    var username = $("#id_username").val();
    var password = $("#id_password").val();
    var site_domain = $("#id_site_domain").val();

    $('#formTitle').html('<h2>Mencoba mendaftarkan akun <br>' + user_id + "</h2>");
    $('#formContainer').html('');
    $('#gearContainer').removeClass('hidden');
    $('#gearContainer').addClass('show');
    $.post($("loginForm").attr("action"),
        {
            csrfmiddlewaretoken:"{{token}}",
            user_id:user_id,
            access_key:access_key,
            username:username,
            password:password,
            site_domain:site_domain
        },
            //or your custom data either as object {foo: "bar", ...} or foo=bar&...
            function (data, status){    
                if(status=='success'){    
                    $('#formTitle').html('<h1 class="success">Pendaftaran Telah Selesai</h1>');
                    $('#gearContainer').removeClass('show');
                    $('#gearContainer').addClass('hidden');
                    $('#formContainer').html("<p style='margin: 50px 0; width:100%; text-align:center'>Anda akan diarahkan ke <br>"+
                        '<span style="font-weight:600; font-size:24pt">'+data['domain']+"</span></p>");
                    setTimeout(function(){
                       window.open(data['redirect_url'], '_self');
                    }, 5000);
                }
                },
        ).fail(function(xhr) {
            if(xhr.status == 403){
                window.open("{% url 'cms:activation' %}?code=403", "_self");
            }else if(xhr.status == 404){
                window.open("{% url 'cms:activation' %}?code=404", "_self");
            }else if(xhr.status == 500){
                window.open("{% url 'cms:activation' %}?code=500", "_self");
            }
        });
    }
</script>