zeon_backend/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dispatcher.views import Index, Blog, Article, Page, Comment, ArticleList, Reply
from django.conf import settings
from django.conf.urls.static import static
from company_profile.cp_admin import urls as cp_admin
from store.st_admin import urls as st_admin

import company_profile.cp_admin.ckeditor_uploader.urls as ckeditor_uploader_urls
import store.st_storefront.urls as storefront
import store.st_database_wilayah.urls as wilayah
import store.st_shopping_cart.urls as cart
import store.st_purchase_order.urls as order
#import shipping_backend.urls as shipping

from store.st_purchase_order.views import checkout, pay, history

urlpatterns = [
    path('wilayah/', include(wilayah, namespace='wilayah_backend')),
    path('cart/', include(cart, namespace='cart_backend')),
    path('checkout/', checkout, name="checkout"),
    path('pay/', pay, name="pay"),
    path('history/', history, name="history"),
    path('order/', include(order, namespace='order_backend')),
    #path('shipping/', include(shipping, namespace='shipping_backend')),
    path('str/', include(st_admin, namespace='st_admin')),
    path('cms/', include(cp_admin, namespace='cp_admin')),
    path('core/admin/', admin.site.urls),
    path('blog/<str:kategori>/<str:slug>/', Article.as_view(), name="blog_detail"),
    path('comment/<str:article_slug>/<str:method>/', Comment.as_view(), name="add_comment"),
    path('comment/<str:article_slug>/', Comment.as_view(), name="view_all_comment"),
    path('reply/<str:article_slug>/<int:comment_pk>/<str:method>/', Reply.as_view(), name="add_reply"),
    re_path(r'^$', Index.as_view()), 
    re_path(r'^blog/$', Blog.as_view(), name="blog_index"),
    re_path(r'^ckeditor/', include(ckeditor_uploader_urls)),
    re_path(r'^store/', include(storefront, namespace='store_backend')),
    re_path(r'^taggit/', include('taggit_selectize.urls')),
    path('<str:page_slug>/', Page.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company_profile/cp_articles/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.dispatch import receiver
from django.utils.crypto import get_random_string

from taggit_selectize.managers import TaggableManager
from ckeditor.fields import RichTextField

from membership.models import Member

import datetime

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True, db_index=True, blank=True, null=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE,related_name='category_site', null=True, blank=True)
    
    def __str__(self):
        return self.title.title()

    def save(self, *args, **kwargs):
        slug = slugify(self.title.lower())
        while Category.objects.filter(slug = slug).exists():
            slug = slugify("%s-%s"%(self.title.lower(),get_random_string(5, allowed_chars='12345677890')))

        self.slug = slug
        super(Category, self).save(*args, **kwargs)

    def get_edit_url(self):
        return "%s" % (reverse('cms:category_edit_delete', kwargs={'action':'edit', 'pk':self.pk}))

    def get_delete_url(self):
        return "%s" % (reverse('cms:category_edit_delete', kwargs={'action':'delete', 'pk':self.pk}))
    
    class Meta:
        verbose_name_plural = "Categories"

class Article(models.Model):
    class_name = models.CharField(max_length=200, blank=True)
    category = models.ManyToManyField(Category, related_name="article_category", blank=True)
    slug = models.SlugField(max_length=200,unique=True, db_index=True, blank=True, null=True)
    tags = TaggableManager(blank=True)
    title = models.CharField(max_length=200)
    lead_in = models.CharField(max_length=1000, default="", blank=True)
    content = RichTextField(null=True, blank=True)
    site = models.ForeignKey(Site, related_name="article_site", on_delete=models.CASCADE,null=True, blank=True)
    author = models.ForeignKey(Member, null=True, blank=True,
                                on_delete=models.CASCADE,
                                related_name="article_author", 
                                verbose_name='author')
    owner = models.ForeignKey(Member, null=True, blank=True,
                                on_delete=models.CASCADE, 
                                related_name="article_owner", 
                                verbose_name='owner')
    created_date = models.DateTimeField(db_index=True,default=datetime.datetime.now)
    published_date = models.DateTimeField(db_index=True,null=True, blank=True)
    is_published = models.BooleanField(default=True, db_index=True)
    is_featured = models.BooleanField(default=False, db_index=True)
    is_preview = models.BooleanField(default=False, db_index=True)
    featured_image = models.ImageField(upload_to = 'cp/user_uploads/featured_images/', null=True, blank=True)
    page_view = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title.title()

            

    def get_all_tags(self):
        return self.tags.all()

    def get_image_url(self):
        return "%s" % ("/media/%s"%self.featured_image)

    def get_article_url(self):
        return "%s" % (reverse('blog_detail', kwargs={'kategori':self.category.all()[0].slug, 'slug':self.slug}))

    def get_edit_url(self):
        return "%s" % (reverse('cms:article_edit_delete', kwargs={'action':'edit', 'pk':self.pk}))

    def get_delete_url(self):
        return "%s" % (reverse('cms:article_edit_delete', kwargs={'action':'delete', 'pk':self.pk}))
    
    def get_class_name(self):
        return self.class_name


@receiver(post_save, sender=Article)
def create_article(sender, instance, created, **kwargs):
    if created:
        slug = slugify(instance.title.lower())
        while Article.objects.filter(slug = slug).exists():
            slug = slugify("%s-%s"%(instance.title.lower(),get_random_string(5, allowed_chars='12345677890')))

        instance.slug = slug
        instance.save()

class TempArticle(Article):
    def save(self, *args, **kwargs):
        temps = TempArticle.objects.all().exclude(pk=self.pk)
        if temps:
            for temp in temps:
                temp.delete()
        self.is_published = False
        self.is_preview = True
        super(TempArticle, self).save(*args, **kwargs)
    


@receiver(post_save, sender=TempArticle)
def create_temp_article(sender, instance, created, **kwargs):
    if created:
        slug = slugify(instance.title.lower())
        while TempArticle.objects.filter(slug = slug).exists():
            slug = slugify("%s-%s"%(instance.title.lower(),get_random_string(5, allowed_chars='12345677890')))

        instance.slug = slug
        instance.save()

company_profile/cp_articles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.middleware.csrf import get_token
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ArticleAddForm, ArticlePreviewForm, CategoryAddForm
from company_profile.cp_articles.models import Article as ArticleModel
from company_profile.cp_articles.models import TempArticle as TempArticleModel
from company_profile.cp_articles.models import Category
from company_profile.cp_user_configs.models import UserConfigs
from dispatcher.views import ComponentRenderer
from dispatcher.views import Dispatcher

import time
from urllib.parse import urlparse

class CPArticle(LoginRequiredMixin, ComponentRenderer, Dispatcher):
    login_url = '/cms/login/'
    template = "cp_admin/index.html"
    component = {}
    component['base'] = 'cp_admin/component/index_base.html'
    component['header'] =  'cp_admin/component/index_header.html'
    index_main = 'cp_articles/component/cms_article_main.html'
    index_local_script = 'cp_articles/component/cms_article_local_script.html'
    add_main = 'cp_articles/component/cms_article_add_main.html'
    add_local_script = 'cp_articles/component/cms_article_add_local_script.html'
    edit_main = 'cp_articles/component/cms_article_edit_main.html'
    edit_local_script = 'cp_articles/component/cms_article_edit_local_script.html'
    index_url = '/cms/article/'
    form = ArticleAddForm()
    def post(self, request, *args, **kwargs):
        data = super(CPArticle, self).get(request, args, kwargs)
        member = data['member']
        site = data['site']
        if  kwargs['action'] == 'edit':
            article = ArticleModel.objects.get(pk=kwargs['pk'])
            self.form = ArticleAddForm(request.POST, request.FILES, instance=article)
            """
            if self.form.is_valid():
                article = self.form.save()
                if not article.category.all() :
                    article.category.add(Category.objects.get_or_create(site=site, title="post")[0])
                    article.save()
                return HttpResponseRedirect(self.index_url)
            """
        elif  kwargs['action'] == 'preview':
            self.form = ArticlePreviewForm(request.POST, request.FILES)
        else:
            self.form = ArticleAddForm(request.POST, request.FILES)

        if self.form.is_valid():
            article = self.form.save(commit=False)
            article.site = site
            article.save()
            self.form.save_m2m()
            if kwargs['action'] != 'preview':
                if not article.category.all() :
                    article.category.add(Category.objects.get_or_create(site=site, title="post")[0])
                    article.save()
            else:
                referer = request.META['HTTP_REFERER']
                if '/cms/article/edit' in referer:
                    parse_object = urlparse(referer)
                    url_splitted = parse_object.path.split("/")
                    try:
                        old_article = ArticleModel.objects.get(pk = url_splitted[-2])
                    except:
                        old_article = ''
                    if old_article and not article.featured_image:
                        article.featured_image = old_article.featured_image
                        article.save()

                if not article.category.all() :
                    article.category.clear()
                    article.category.add(Category.objects.get_or_create(site=site, title="preview")[0])
                    article.save()
            if kwargs['action'] == 'preview':
                article.class_name='TempArticle'
                article.save()
                return JsonResponse({'url': article.get_article_url()}, status=200)

            return HttpResponseRedirect(self.index_url)

        self.form.fields["category"].queryset = Category.objects.filter(site=site)
        token = get_token(request)
        configs = UserConfigs.objects.get(member = member)
        return render(request, self.template, {
                'form': self.form,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component
            }
        )

    def get(self, request, *args, **kwargs):
        if  kwargs['action'] == 'delete' or kwargs['action'] == 'edit':
            if kwargs['pk'] == 'none':
                return HttpResponseRedirect(self.index_url)
            else :
                try:
                    article = ArticleModel.objects.get(pk=kwargs['pk'])
                except:
                    return HttpResponseRedirect(self.index_url)
        method = request.GET.get('method', '')
        data = super(CPArticle, self).get(request, args, kwargs)
        token = get_token(request)
        member = data['member']
        configs = UserConfigs.objects.get(member = member)
        site = data['site']
        form = self.form
        featured_image = ''
        if  kwargs['action'] == 'edit':
            featured_image = article.get_image_url()
            form = ArticleAddForm(instance=article)
        elif  kwargs['action'] == 'delete':
            article.delete()
            return HttpResponseRedirect(self.index_url)

        if kwargs['action'] == 'show_all' or \
            kwargs['action'] == 'add' or \
            kwargs['action'] == 'edit':
            self.set_component(kwargs)
        else :
            return HttpResponseRedirect(self.index_url)

        form.fields["category"].queryset = Category.objects.filter(site=site)

        if method == 'get_component':
            return self.get_component(request, token, data, configs, site, member, form, featured_image)

        return render(request, self.template, {
                'form': form,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component,
                'featured_image' : featured_image,
            }
        )


class CPCategory(LoginRequiredMixin, ComponentRenderer, Dispatcher):
    login_url = '/cms/login/'
    template = "cp_admin/index.html"
    component = {}
    component['base'] = 'cp_admin/component/index_base.html'
    component['header'] =  'cp_admin/component/index_header.html'
    index_main = 'cp_articles/component/cms_category_main.html'
    index_local_script = 'cp_articles/component/cms_category_local_script.html'
    add_main = 'cp_articles/component/cms_category_add_main.html'
    add_local_script = 'cp_articles/component/cms_category_add_local_script.html'
    edit_main = 'cp_articles/component/cms_category_edit_main.html'
    edit_local_script = 'cp_articles/component/cms_category_edit_local_script.html'
    index_url = '/cms/category/'
    form = CategoryAddForm()

    def post(self, request, *args, **kwargs):
        data = super(CPCategory, self).get(request, args, kwargs)
        member = data['member']
        site = data['site']
        if  kwargs['action'] == 'edit':
            category = Category.objects.get(pk=kwargs['pk'])
            self.form = CategoryAddForm(request.POST, request.FILES, instance=category)
            if self.form.is_valid():
                category = self.form.save()
                return HttpResponseRedirect(self.index_url)
        else:
            self.form = CategoryAddForm(request.POST, request.FILES)

        if self.form.is_valid():
            category = self.form.save(commit=False)
            category.site = site
            category.save()

            return HttpResponseRedirect(self.index_url)

        token = get_token(request)
        configs = UserConfigs.objects.get(member = member)
        return render(request, self.template, {
                'form': self.form,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component
            }
        )

    def get(self, request, *args, **kwargs):
        category = ""
        if  kwargs['action'] == 'delete':
            if kwargs['pk'] == 'none':
                return HttpResponseRedirect(self.index_url)
            else :
                try:
                    category = Category.objects.get(pk=kwargs['pk'])
                except:
                    return HttpResponseRedirect(self.index_url)
        if category.title == 'post':
            return HttpResponseRedirect(self.index_url)

        method = request.GET.get('method', '')
        data = super(CPCategory, self).get(request, args, kwargs)
        token = get_token(request)
        member = data['member']
        configs = UserConfigs.objects.get(member = member)
        site = data['site']
        form = self.form
        featured_image = ''
        if  kwargs['action'] == 'edit':
            try:
                category = Category.objects.get(pk=kwargs['pk'])
            except:
                return HttpResponseRedirect(self.index_url)
            form = CategoryAddForm(instance=category)

        elif  kwargs['action'] == 'delete':
            articles = ArticleModel.objects.filter(category=category)
            if articles:
                for article in articles:
                    try:
                        article.category.remove(category)
                    except:
                        pass
            category.delete()
            return HttpResponseRedirect(self.index_url)

        if kwargs['action'] == 'show_all' or \
            kwargs['action'] == 'add' or \
            kwargs['action'] == 'edit' :
            self.set_component(kwargs)
        else :
            return HttpResponseRedirect(self.index_url)

        if method == 'get_component':

company_profile/cp_articles/templates/cp_articles/component/cms_article_add_local_script.html
<script>
    function localScript(){
        $('#id_is_published').bootstrapToggle();
        $('#id_is_featured').bootstrapToggle();
        var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
        for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '1') {
                t.setAttribute('data-processed', '0');
            }
        }
        function initialiseCKEditor() {
            var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
            for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '0' && t.id.indexOf('__prefix__') == -1) {
                t.setAttribute('data-processed', '1');
                var ext = JSON.parse(t.getAttribute('data-external-plugin-resources'));
                for (var j=0; j<ext.length; ++j) {
                CKEDITOR.plugins.addExternal(ext[j][0], ext[j][1], ext[j][2]);
                }
                CKEDITOR.replace(t.id, JSON.parse(t.getAttribute('data-config')));
            }
            }
        }
        
        function initialiseCKEditorInInlinedForms() {
            document.body.addEventListener('click', function(e) {
            if (e.target && (
                e.target.matches('.add-row a') ||
                e.target.matches('.grp-add-handler')
            )) {
                initialiseCKEditor();
            }
            });
        }
        
        setTimeout(initialiseCKEditor(), 4000);
        
        setTimeout(initialiseCKEditorInInlinedForms(), 4000);
    }
    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
    function previewNewArticle(){
        CKEDITOR.instances['id_content'].updateElement();
        var formData = new FormData($('#addArticleForm')[0]);
        $.ajax({
            url: '/cms/article/preview/',
            type: 'POST',
            data: formData,
            async: false,
            success: function (data) {
                window.open(data['url'], '_blank')
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
    try {
        ($('#id_is_published').bootstrapToggle())();
        ($('#id_is_featured').bootstrapToggle())();
        throw "Exception"; // generates an exception
    }
    catch (e) {}
</script>

company_profile/cp_articles/templates/cp_articles/component/cms_article_add_main.html
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/cms/')">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/cms/article/')">Article</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add</li>
        </ol>
    </nav>
{% endblock %}

<div class="row">
    <div class="col-sm-12">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="col-sm-12">
        <form id='addArticleForm' method="POST" enctype="multipart/form-data">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{token}}">
            <div class="row">
                <!-- column -->
                <div class="col-xs-12 col-sm-9">
                    <div class="card">
                        <div class="card-body">
                            <h1>Add New Article</h1>
                            <hr>
                            <h4>{{ form.title.label }}</h4>
                            {{ form.title }}
                            <br>
                            <br>
                            <h4>{{ form.lead_in.label }}</h4>
                            {{ form.lead_in }}
                            <br>
                            <br>
                            <h4>{{ form.content.label }}</h4>
                            {{ form.content }}
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                    <div class="card">
                        <div class="card-body">
                            <h6>{{ form.tags.label }}</h6>
                            {{ form.tags }}
                            <h6>{{ form.category.label }}</h6>
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h6>{{ form.published_date }}  {{ form.published_date.label }}</h6>
                            <h6>{{ form.is_published }}  {{ form.is_published.label }}</h6>
                            <h6>{{ form.is_featured }}  {{ form.is_featured.label }}</h6>
                            <h6>{{ form.featured_image.label }}</h6>
                            {{ form.featured_image }}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body" style="display: flex; justify-content: center">
                            <p class="btn btn-info" style="margin: auto" onclick="previewNewArticle()">PREVIEW</p>
                            <p class="btn btn-primary" style="margin: auto" onclick="submitNewArticle()">SUBMIT</p>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

company_profile/cp_articles/templates/cp_articles/component/cms_article_edit_local_script.html
<script>
    function localScript(){
        var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
        for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '1') {
                t.setAttribute('data-processed', '0');
            }
        }
        function initialiseCKEditor() {
            var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
            for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '0' && t.id.indexOf('__prefix__') == -1) {
                t.setAttribute('data-processed', '1');
                var ext = JSON.parse(t.getAttribute('data-external-plugin-resources'));
                for (var j=0; j<ext.length; ++j) {
                CKEDITOR.plugins.addExternal(ext[j][0], ext[j][1], ext[j][2]);
                }
                CKEDITOR.replace(t.id, JSON.parse(t.getAttribute('data-config')));
            }
            }
        }
        
        function initialiseCKEditorInInlinedForms() {
            document.body.addEventListener('click', function(e) {
            if (e.target && (
                e.target.matches('.add-row a') ||
                e.target.matches('.grp-add-handler')
            )) {
                initialiseCKEditor();
            }
            });
        }
        
        setTimeout(initialiseCKEditor(), 4000);
        
        setTimeout(initialiseCKEditorInInlinedForms(), 4000);
    }

    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
    function previewNewArticle(){
        CKEDITOR.instances['id_content'].updateElement();
        var formData = new FormData($('#editArticleForm')[0]);
        $.ajax({
            url: '/cms/article/preview/',
            type: 'POST',
            data: formData,
            async: false,
            success: function (data) {
                window.open(data['url'], '_blank')
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
    try {
        ($('#id_is_published').bootstrapToggle())();
        ($('#id_is_featured').bootstrapToggle())();
        throw "Exception"; // generates an exception
    }
    catch (e) {}
    
</script>

company_profile/cp_articles/templates/cp_articles/component/cms_article_edit_main.html
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/cms/')">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/cms/page/')">Article</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </ol>
    </nav>
{% endblock %}

<div class="row">
    <div class="col-sm-12">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    <p>{{ field.label }}</p>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="col-sm-12">
        <form id='editArticleForm' method="POST" enctype="multipart/form-data">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{token}}">
            <div class="row">
                <!-- column -->
                <div class="col-xs-12 col-sm-9">
                    <div class="card">
                        <div class="card-body">
                            <h1>Add New Article</h1>
                            <hr>
                            {% csrf_token %}
                            <h4>{{ form.title.label }}</h4>
                            {{ form.title }}
                            <br>
                            <br>
                            <h4>{{ form.content.label }}</h4>
                            {{ form.content }}
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                    <div class="card">
                        <div class="card-body">
                            <h6>{{ form.tags.label }}</h6>
                            {{ form.tags }}
                            <h6>{{ form.category.label }}</h6>
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h6>{{ form.published_date }}  {{ form.published_date.label }}</h6>
                            <h6>{{ form.is_published }}  {{ form.is_published.label }}</h6>
                            <h6>{{ form.is_featured }}  {{ form.is_featured.label }}</h6>
                            <hr>
                            <h6>{{ form.featured_image.label }}</h6>
                            {% if featured_image %}
                            <img src="{{ featured_image }}" width="100%; height:auto">
                            <hr>
                            {% endif %}
                            {{ form.featured_image }}
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body" style="display: flex; justify-content: center">
                            <p class="btn btn-info" style="margin: auto" onclick="previewNewArticle()">PREVIEW</p>
                            <button class="btn btn-primary" form="editArticleForm" style="margin: auto" type="submit">SUBMIT</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

company_profile/cp_articles/templates/cp_articles/component/cms_article_local_script.html
<script>
    function localScript(){
        var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
        for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '1') {
                t.setAttribute('data-processed', '0');
            }
        }
        function initialiseCKEditor() {
            var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
            for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '0' && t.id.indexOf('__prefix__') == -1) {
                t.setAttribute('data-processed', '1');
                var ext = JSON.parse(t.getAttribute('data-external-plugin-resources'));
                for (var j=0; j<ext.length; ++j) {
                CKEDITOR.plugins.addExternal(ext[j][0], ext[j][1], ext[j][2]);
                }
                CKEDITOR.replace(t.id, JSON.parse(t.getAttribute('data-config')));
            }
            }
        }
        
        function initialiseCKEditorInInlinedForms() {
            document.body.addEventListener('click', function(e) {
            if (e.target && (
                e.target.matches('.add-row a') ||
                e.target.matches('.grp-add-handler')
            )) {
                initialiseCKEditor();
            }
            });
        }
        
        setTimeout(initialiseCKEditor(), 4000);
        
        setTimeout(initialiseCKEditorInInlinedForms(), 4000);
    }

    
</script>

company_profile/cp_articles/templates/cp_articles/component/cms_category_add_local_script.html
<script>
    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
</script>

company_profile/cp_articles/templates/cp_articles/component/cms_category_edit_local_script.html
<script>
    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
</script>

company_profile/cp_articles/templates/cp_articles/component/cms_category_local_script.html
<script>
</script>