zeon_backend/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dispatcher.views import Index, Blog, Article, Page, Comment, ArticleList, Reply
from django.conf import settings
from django.conf.urls.static import static
from company_profile.cp_admin import urls as cp_admin
from store.st_admin import urls as st_admin

import company_profile.cp_admin.ckeditor_uploader.urls as ckeditor_uploader_urls
import store.st_storefront.urls as storefront
import store.st_database_wilayah.urls as wilayah
import store.st_shopping_cart.urls as cart
import store.st_purchase_order.urls as order
#import shipping_backend.urls as shipping

from store.st_purchase_order.views import checkout, pay, history

urlpatterns = [
    path('wilayah/', include(wilayah, namespace='wilayah_backend')),
    path('cart/', include(cart, namespace='cart_backend')),
    path('checkout/', checkout, name="checkout"),
    path('pay/', pay, name="pay"),
    path('history/', history, name="history"),
    path('order/', include(order, namespace='order_backend')),
    #path('shipping/', include(shipping, namespace='shipping_backend')),
    path('str/', include(st_admin, namespace='st_admin')),
    path('cms/', include(cp_admin, namespace='cp_admin')),
    path('core/admin/', admin.site.urls),
    path('blog/<str:kategori>/<str:slug>/', Article.as_view(), name="blog_detail"),
    path('comment/<str:article_slug>/<str:method>/', Comment.as_view(), name="add_comment"),
    path('comment/<str:article_slug>/', Comment.as_view(), name="view_all_comment"),
    path('reply/<str:article_slug>/<int:comment_pk>/<str:method>/', Reply.as_view(), name="add_reply"),
    re_path(r'^$', Index.as_view()), 
    re_path(r'^blog/$', Blog.as_view(), name="blog_index"),
    re_path(r'^ckeditor/', include(ckeditor_uploader_urls)),
    re_path(r'^store/', include(storefront, namespace='store_backend')),
    re_path(r'^taggit/', include('taggit_selectize.urls')),
    path('<str:page_slug>/', Page.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/st_catalog/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(db_index=True,
            max_length = 100,
            help_text="Nama Kategori")
    slug = AutoSlugField(max_length=100, 
            unique=True, 
            db_index=True,
            populate_from=('name',))
    description = models.TextField(blank=True,
            help_text="Deskripsi Kategori")
    is_archived = models.BooleanField(default = False,
            help_text="Centang untuk Menyembunyikan Kategori") 
    site = models.ForeignKey(Site, on_delete=models.CASCADE,related_name='product_category_site', null=True, blank=True)
   
    class Meta:
        verbose_name_plural = "Categories"

    def get_edit_url(self):
        return "%s" % (reverse('store:category_edit_delete', kwargs={'action':'edit', 'pk':self.pk}))

    def get_delete_url(self):
        return "%s" % (reverse('store:category_edit_delete', kwargs={'action':'delete', 'pk':self.pk}))
   

    def __str__(self):
       return self.name

    def get_url(self):
        return "/store/kategori/%s/" % (self.pk)


class Product(models.Model):
    name = models.CharField(max_length = 200,
            db_index=True,
            help_text="Nama Produk")
    slug = AutoSlugField(max_length=100, 
            db_index=True,
            unique=True, 
            populate_from=('name',))
    description = models.TextField(help_text="Deskripsi Produk")
    photo = models.ImageField(upload_to = 'product_photo',
            help_text="Foto Produk")
    photo_alt1 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 1")
    photo_alt2 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 2")
    photo_alt3 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 3")
    photo_alt4 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 4")
    photo_alt5 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 5")
    price = models.PositiveIntegerField(null=True, help_text="Harga Produk")

    unit_weight = models.PositiveIntegerField(null=True, help_text="Berat Satuan Produk dalam gram")
    is_available = models.BooleanField(default = True,
            help_text="Centang Jika Produk Tersedia")
    is_featured = models.BooleanField(default = False,
            help_text="Centang untuk menjadikan unggulan")
    is_archived = models.BooleanField(default = False,
            help_text="Centang untuk Menyembunyikan Produk")
    categories = models.ManyToManyField(Category, 
            related_name="products_in_category",
            help_text="Kategori Produk")
    site = models.ForeignKey(Site, on_delete=models.CASCADE,related_name='product_site', null=True, blank=True)
    
    def get_details(self):
        details = {'name': self.name,
                   'weight' : self.unit_weight,
                   'price' : self.price}
        return details

    def get_photo_url(self):
        return "/media/%s" % (self.photo)

    def get_photo_alt1_url(self):
        return "/media/%s" % (self.photo_alt1)
    def get_photo_alt2_url(self):
        return "/media/%s" % (self.photo_alt2)
    def get_photo_alt3_url(self):
        return "/media/%s" % (self.photo_alt3)
    def get_photo_alt4_url(self):
        return "/media/%s" % (self.photo_alt4)
    def get_photo_alt5_url(self):
        return "/media/%s" % (self.photo_alt5)

    def get_edit_url(self):
        return "%s" % (reverse('store:product_edit_delete', kwargs={'action':'edit', 'pk':self.pk}))

    def get_delete_url(self):
        return "%s" % (reverse('store:product_edit_delete', kwargs={'action':'delete', 'pk':self.pk}))
    
    def get_detail_url(self):
        return reverse('storefront:product_detail', kwargs={'product_pk':self.pk})

    class Meta:
        verbose_name_plural = "Products"

    def __str__(self):
       return self.name

store/st_catalog/forms.py
from django import forms
from .models import Product, Category

class CategoryAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CategoryAddForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['style'] = 'width:100%; padding:10px'
    class Meta:
        model = Category
        fields = ('name',)

class ProductAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductAddForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs['rows'] = '13'
        self.fields['description'].widget.attrs['style'] = 'width:100%; padding:10px'
        self.fields['description'].widget.attrs['placeholder'] = ''
        self.fields['categories'].help_text = 'Pilih Kategori Artikel *(bisa lebih dari 1)'
        self.fields['categories'].widget.attrs['style'] = 'width:100%; padding:10px'
        self.fields['name'].widget.attrs['style'] = 'width:100%; padding:10px'
        self.fields['is_available'].widget.attrs['style'] = 'margin:10px 10px 0 0'
        self.fields['is_available'].widget.attrs['data-toggle'] = 'toggle'
        self.fields['is_archived'].widget.attrs['style'] = 'margin:10px 10px 0 0'
        self.fields['is_archived'].widget.attrs['data-toggle'] = 'toggle'
        self.fields['price'].widget.attrs['style'] = 'width:100%; padding:10px'
        self.fields['unit_weight'].widget.attrs['style'] = 'width:100%; padding:10px'
        
        
    class Meta:
        model = Product
        fields = ('name',
                'description',
                'photo',
                'photo_alt1',
                'photo_alt2',
                'photo_alt3',
                'photo_alt4',
                'photo_alt5',
                'unit_weight',
                'categories',
                'is_available',
                'is_archived',
                'price',)

store/st_catalog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.middleware.csrf import get_token
from django.contrib.auth.mixins import LoginRequiredMixin
from dispatcher.views import Dispatcher
from dispatcher.views import ComponentRenderer

from company_profile.cp_user_configs.models import UserConfigs

from .models import Product, Category
from .forms import ProductAddForm, CategoryAddForm

class STProduct(LoginRequiredMixin, ComponentRenderer, Dispatcher):
    login_url = '/cms/login/'
    template = "cp_admin/index.html"
    component = {}
    component['base'] = 'cp_admin/component/index_base.html'
    component['header'] =  'cp_admin/component/index_header.html'
    index_main = 'st_catalog/component/product_main.html'
    index_local_script = 'st_catalog/component/product_local_script.html'
    add_main = 'st_catalog/component/product_add_main.html'
    add_local_script = 'st_catalog/component/product_add_local_script.html'
    edit_main = 'st_catalog/component/product_edit_main.html'
    edit_local_script = 'st_catalog/component/product_edit_local_script.html'
    index_url = '/str/product/'
    form = ProductAddForm()
    def post(self, request, *args, **kwargs):
        data = super(STProduct, self).get(request, args, kwargs)
        member = data['member']
        site = data['site']
        if  kwargs['action'] == 'edit':
            product = Product.objects.get(pk=kwargs['pk'])
            self.form = ProductAddForm(request.POST, request.FILES, instance=product)
        else:
            self.form = ProductAddForm(request.POST, request.FILES)

        if self.form.is_valid():
            product = self.form.save(commit=False)
            product.site = site
            product.save()
            self.form.save_m2m()

            if kwargs['action'] != 'preview':
                if not product.categories.all() :
                    product.categories.add(Category.objects.get_or_create(site=site, name="default")[0])
                    product.save()

            return HttpResponseRedirect(self.index_url)

        self.form.fields["categories"].queryset = Category.objects.filter(site=site)
        token = get_token(request)
        configs = UserConfigs.objects.get(member = member)
        return render(request, self.template, {
                'form': self.form,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component
            }
        )


    def get(self, request, *args, **kwargs):
        if  kwargs['action'] == 'delete' or kwargs['action'] == 'edit':
            if kwargs['pk'] == 'none':
                return HttpResponseRedirect(self.index_url)
            else :
                try:
                    product = Product.objects.get(pk=kwargs['pk'])
                except:
                    return HttpResponseRedirect(self.index_url)
        method = request.GET.get('method', '')
        data = super(STProduct, self).get(request, args, kwargs)
        token = get_token(request)
        member = data['member']
        configs = UserConfigs.objects.get(member = member)
        site = data['site']
        form = self.form
        featured_image = ''

        if  kwargs['action'] == 'edit':
            form = ProductAddForm(instance=product)
        elif  kwargs['action'] == 'delete':
            product.delete()
            return HttpResponseRedirect(self.index_url)

        if kwargs['action'] == 'show_all' or \
            kwargs['action'] == 'add' or \
            kwargs['action'] == 'edit' or \
            kwargs['action'] == 'delete' :
            self.set_component(kwargs)
        else :
            return HttpResponseRedirect(self.index_url)

        form.fields["categories"].queryset = Category.objects.filter(site=site)

        if method == 'get_component':
            return self.get_component(request, token, data, configs, site, member, form, featured_image)

        return render(request, self.template, {
                'form': form,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component,
                'featured_image' : featured_image,
            }
        )

class STCategory(LoginRequiredMixin, ComponentRenderer, Dispatcher):
    login_url = '/cms/login/'
    template = "cp_admin/index.html"
    component = {}
    component['base'] = 'cp_admin/component/index_base.html'
    component['header'] =  'cp_admin/component/index_header.html'
    index_main = 'st_catalog/component/category_main.html'
    index_local_script = 'st_catalog/component/category_local_script.html'
    add_main = 'st_catalog/component/category_add_main.html'
    add_local_script = 'st_catalog/component/category_add_local_script.html'
    edit_main = 'st_catalog/component/category_edit_main.html'
    edit_local_script = 'st_catalog/component/category_edit_local_script.html'
    index_url = '/str/category/'
    form = CategoryAddForm()

    def post(self, request, *args, **kwargs):
        data = super(STCategory, self).get(request, args, kwargs)
        member = data['member']
        site = data['site']
        if  kwargs['action'] == 'edit':
            category = Category.objects.get(pk=kwargs['pk'])
            self.form = CategoryAddForm(request.POST, request.FILES, instance=category)
            if self.form.is_valid():
                category = self.form.save()
                return HttpResponseRedirect(self.index_url)
        else:
            self.form = CategoryAddForm(request.POST, request.FILES)

        if self.form.is_valid():
            category = self.form.save(commit=False)
            category.site = site
            category.save()

            return HttpResponseRedirect(self.index_url)

        token = get_token(request)
        configs = UserConfigs.objects.get(member = member)
        return render(request, self.template, {
                'form': self.form,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component
            }
        )
        
    def get(self, request, *args, **kwargs):
        category = ""
        if  kwargs['action'] == 'delete':
            if kwargs['pk'] == 'none':
                return HttpResponseRedirect(self.index_url)
            else :
                try:
                    category = Category.objects.get(pk=kwargs['pk'])
                except:
                    return HttpResponseRedirect(self.index_url)
            if category.name == 'post':
                return HttpResponseRedirect(self.index_url)

        method = request.GET.get('method', '')
        data = super(STCategory, self).get(request, args, kwargs)
        token = get_token(request)
        member = data['member']
        configs = UserConfigs.objects.get(member = member)
        site = data['site']
        form = self.form
        featured_image = ''
        if  kwargs['action'] == 'edit':
            try:
                category = Category.objects.get(pk=kwargs['pk'])
            except:
                return HttpResponseRedirect(self.index_url)
            form = CategoryAddForm(instance=category)

        elif  kwargs['action'] == 'delete':
            products = Product.objects.filter(categories=category)
            if products:
                for product in products:
                    try:
                        product.categories.remove(category)
                    except:
                        pass
            category.delete()
            return HttpResponseRedirect(self.index_url)

        
        if kwargs['action'] == 'show_all' or \
            kwargs['action'] == 'add' or \
            kwargs['action'] == 'edit' or \
            kwargs['action'] == 'delete' :
            self.set_component(kwargs)
        else :
            return HttpResponseRedirect(self.index_url)

        if method == 'get_component':
            return self.get_component(request, token, data, configs, site, member, form, featured_image)

        return render(request, self.template, {
                'form': form,
                'featured_image': featured_image,
                'member': member,
                'data': data,
                'configs': configs,
                'site': site,
                'token': token,
                'component':self.component,
            }
        )

store/st_catalog/templates/st_catalog/component/category_add_local_script .html
<script>
    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
</script>

store/st_catalog/templates/st_catalog/component/category_add_local_script.html
<script>
    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
</script>

store/st_catalog/templates/st_catalog/component/category_add_main.html
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/')">Store</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/category/')">Category</a></li>
            <li class="breadcrumb-item active" aria-current="page">Add</li>
        </ol>
    </nav>
{% endblock %}


<div class="row">
    <div class="col-sm-12">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="col-sm-12">
        <form id='addArticleForm' method="POST" enctype="multipart/form-data">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{token}}">
            <div class="row">
                <!-- column -->
                <div class="col-xs-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <h1>Add New Category</h1>
                            <hr>
                            <h4>Category Name</h4>
                            <div class="row">
                                <div class="col-xs-12 col-sm-9">
                                    {{ form.name }}
                                </div>
                                <div class="col-xs-12 col-sm-3">
                                    <p class="btn btn-primary" style="margin: auto" onclick="submitNewArticle()">SUBMIT</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

store/st_catalog/templates/st_catalog/component/category_main.html
{% load humanize %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/')">Store</a></li>
            <li class="breadcrumb-item active" aria-current="page">Category</li>
        </ol>
    </nav>
{% endblock %}

<div class="row">
    <!-- column -->
    <div class="col-sm-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="row" style="margin: 0">
                    <div class="col-xs-10 col-sm-10" style="text-align: left">
                        <h3>Categories </h3>
                        <p>Total Category: {{ site.product_category_site.all | length }}</p>
                    </div>
                    <div class="col-xs-2 col-sm-2" style="text-align: right; display: flex; flex-direction: column; justify-content: flex-end">
                        <p onclick="getNext('/str/category/add/')" class="btn btn-primary btn-md"><span class="fa fa-plus"></span> CREATE NEW</p>
                    </div>
                </div>
                <hr>
                <div class="row" style="margin: 0">
                    <div class="col-xs-4 col-sm-4" style="text-align: left">
                        <h6>Title</h6>
                    </div>
                    <div class="col-xs-4 col-sm-2" style="text-align: left">
                    </div>
                </div>
                <hr>
                {% for category in site.product_category_site.all %}
                    {% if not category.title == 'preview' %}
                        <div class="row" style="margin: 0">
                            <div class="col-xs-4 col-sm-4" style="text-align: left; word-wrap: break-word">
                                <p onclick="window.open('/{{ category.slug }}', '_blank')" style="cursor:pointer" class="text-info">{{ category.name | title }}</p>
                            </div>
                            <div class="col-xs-4 col-sm-2" style="display: flex; justify-content: center">
                                <p onclick="getNext('{{ category.get_edit_url }}')" class="btn btn-info btn-xs" style="margin: auto"><span class="fa fa-edit"></span> EDIT</p>
                                <p onclick="window.open('{{ category.get_delete_url }}', '_parent')" class="btn btn-danger btn-xs" style="margin: auto"><span class="fa fa-trash"></span> DELETE</p>
                            </div>
                            <div class="col-xs-4 col-sm-6">
                            </div>
                            <div class="col-xs-12 col-sm-12" style="word-wrap:break-word">
                                {% for product in category.products_in_category.all %}
                                    {% if forloop.first %}
                                    <p>Product in this category :</p>
                                    <div style="padding-left:25px">
                                    <h6>Name</h6>{% endif %}
                                    
                                    <p onclick="window.open('{{ product.get_detail_url }}', '_blank')" style="cursor:pointer" class="text-info">{{ product.name | title }}</p>
                                    {% if forloop.last %} 
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- column -->
</div>

store/st_catalog/templates/st_catalog/component/product_add_local_script.html
<script>
    function localScript(){
        $('#id_is_available').bootstrapToggle();
        $('#id_is_archived').bootstrapToggle();
    }
    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
    try {
        ($('#id_is_available').bootstrapToggle())();
        ($('#id_is_available').bootstrapToggle())();
        throw "Exception"; // generates an exception
    }
    catch (e) {}
</script>

store/st_catalog/templates/st_catalog/component/product_edit_local_script.html
<script>
    function localScript(){
        var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
        for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '1') {
                t.setAttribute('data-processed', '0');
            }
        }
        function initialiseCKEditor() {
            var textareas = Array.prototype.slice.call(document.querySelectorAll('textarea[data-type=ckeditortype]'));
            for (var i=0; i<textareas.length; ++i) {
            var t = textareas[i];
            if (t.getAttribute('data-processed') == '0' && t.id.indexOf('__prefix__') == -1) {
                t.setAttribute('data-processed', '1');
                var ext = JSON.parse(t.getAttribute('data-external-plugin-resources'));
                for (var j=0; j<ext.length; ++j) {
                CKEDITOR.plugins.addExternal(ext[j][0], ext[j][1], ext[j][2]);
                }
                CKEDITOR.replace(t.id, JSON.parse(t.getAttribute('data-config')));
            }
            }
        }
        
        function initialiseCKEditorInInlinedForms() {
            document.body.addEventListener('click', function(e) {
            if (e.target && (
                e.target.matches('.add-row a') ||
                e.target.matches('.grp-add-handler')
            )) {
                initialiseCKEditor();
            }
            });
        }
        
        setTimeout(initialiseCKEditor(), 4000);
        
        setTimeout(initialiseCKEditorInInlinedForms(), 4000);
    }

    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
    function previewNewArticle(){
        CKEDITOR.instances['id_content'].updateElement();
        var formData = new FormData($('#editArticleForm')[0]);
        $.ajax({
            url: '/cms/article/preview/',
            type: 'POST',
            data: formData,
            async: false,
            success: function (data) {
                window.open(data['url'], '_blank')
            },
            cache: false,
            contentType: false,
            processData: false
        });
    }
    try {
        ($('#id_is_published').bootstrapToggle())();
        ($('#id_is_featured').bootstrapToggle())();
        throw "Exception"; // generates an exception
    }
    catch (e) {}
    
</script>

store/st_catalog/templates/st_catalog/component/product_local_script.html
<script>
    function localScript(){
    }
</script>

store/st_catalog/templates/st_catalog/component/product_main.html
{% load humanize int_to_rupiah int_to_kilogram %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/')">Store</a></li>
            <li class="breadcrumb-item active" aria-current="page">Product</li>
        </ol>
    </nav>
{% endblock %}

<div class="row">
    <!-- column -->
    <div class="col-sm-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="row" style="margin: 0">
                    <div class="col-xs-10 col-sm-10" style="text-align: left">
                        <h3>Product </h3>
                        <p>Total product: {{ site.product_site.all | length }}</p>
                    </div>
                    <div class="col-xs-2 col-sm-2" style="text-align: right; display: flex; flex-direction: column; justify-content: flex-end">
                        <p onclick="getNext('/str/product/add/')" class="btn btn-primary btn-md"><span class="fa fa-plus"></span> CREATE NEW</p>
                    </div>
                </div>
                <hr>
                <div class="row" style="margin:0">
                    <div class="col-xs-4 col-sm-3" style="text-align: left">
                        <h6>Name</h6>
                    </div>
                    <div class="col-xs-4 col-sm-1" style="text-align: left">
                        <h6>Price</h6>
                    </div>
                    <div class="col-xs-4 col-sm-1" style="text-align: left">
                        <h6>Unit Weight</h6>
                    </div>
                    <div class="col-xs-4 col-sm-2" style="text-align: left">
                        <h6>Categories</h6>
                    </div>
                    <div class="col-xs-4 col-sm-2" style="text-align: left">
                    </div>
                </div>
                <hr>
                {% for product in site.product_site.all %}
                    <div class="row" style="margin: 0">
                        <div class="col-xs-2 col-sm-1" style="text-align: center">
                            <img src="{{ product.get_photo_url }}" style="width:100%; height:auto">
                        </div>
                        <div class="col-xs-2 col-sm-1" style="text-align: center">
                            {% if  product.is_available %}
                            <span class="text-success fa fa-check"></span>
                            {% else %}
                            <span class="text-danger fa fa-times"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-2 col-sm-1" style="text-align: center">
                            {% if  product.is_archived %}
                            <span class="text-success fa fa-check"></span>
                            {% else %}
                            <span class="text-danger fa fa-times"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-4 col-sm-3" style="text-align: left; word-wrap: break-word">
                            <p onclick="window.open('{{ product.get_detail_url }}', '_blank')" style="cursor:pointer" class="text-info">{{ product.name | title }}</p>
                        </div>
                        <div class="col-xs-4 col-sm-1" style="text-align: left">
                            <p>{{ product.price | int_to_rupiah }}</p>
                        </div>
                        <div class="col-xs-4 col-sm-1" style="text-align: left">
                            <p>{{ product.unit_weight | int_to_kilogram }}</p>
                        </div>
                        <div class="col-xs-4 col-sm-2" style="text-align: left; word-wrap: break-word">
                            {% for category in product.categories.all %}
                                <span style="display: inline-block; margin: 2px 0"  class="label label-info">{{ category.name | title }}</span>
                            {% endfor %}
                        </div>
                        <div class="col-xs-4 col-sm-2" style="display: flex; justify-content: center">
                            <p onclick="getNext('{{ product.get_edit_url }}')" class="btn btn-info btn-xs" style="margin: auto"><span class="fa fa-edit"></span> EDIT</p>
                            <p onclick="window.open('{{ product.get_delete_url }}', '_parent')" class="btn btn-danger btn-xs" style="margin: auto"><span class="fa fa-trash"></span> DELETE</p>
                        </div>
                    </div>
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- column -->
</div>