store/st_purchase_order/urls.py
from django.urls import path, re_path
from . import views

app_name = 'order'

urlpatterns = [
    path('detail/<str:order_number>/', views.detail, name='detail'),
    path('checkout/', views.checkout, name='chekout'),
    path('history/', views.history, name='history'),
    re_path(r'$', views.index, name='prepare'),
]

zeon_backend/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dispatcher.views import Index, Blog, Article, Page, Comment, ArticleList, Reply
from django.conf import settings
from django.conf.urls.static import static
from company_profile.cp_admin import urls as cp_admin
from store.st_admin import urls as st_admin

import company_profile.cp_admin.ckeditor_uploader.urls as ckeditor_uploader_urls
import store.st_storefront.urls as storefront
import store.st_database_wilayah.urls as wilayah
import store.st_shopping_cart.urls as cart
import store.st_purchase_order.urls as order
#import shipping_backend.urls as shipping

from store.st_purchase_order.views import checkout, pay, history

urlpatterns = [
    path('wilayah/', include(wilayah, namespace='wilayah_backend')),
    path('cart/', include(cart, namespace='cart_backend')),
    path('checkout/', checkout, name="checkout"),
    path('pay/', pay, name="pay"),
    path('history/', history, name="history"),
    path('order/', include(order, namespace='order_backend')),
    #path('shipping/', include(shipping, namespace='shipping_backend')),
    path('str/', include(st_admin, namespace='st_admin')),
    path('cms/', include(cp_admin, namespace='cp_admin')),
    path('core/admin/', admin.site.urls),
    path('blog/<str:kategori>/<str:slug>/', Article.as_view(), name="blog_detail"),
    path('comment/<str:article_slug>/<str:method>/', Comment.as_view(), name="add_comment"),
    path('comment/<str:article_slug>/', Comment.as_view(), name="view_all_comment"),
    path('reply/<str:article_slug>/<int:comment_pk>/<str:method>/', Reply.as_view(), name="add_reply"),
    re_path(r'^$', Index.as_view()), 
    re_path(r'^blog/$', Blog.as_view(), name="blog_index"),
    re_path(r'^ckeditor/', include(ckeditor_uploader_urls)),
    re_path(r'^store/', include(storefront, namespace='store_backend')),
    re_path(r'^taggit/', include('taggit_selectize.urls')),
    path('<str:page_slug>/', Page.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/st_catalog/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(db_index=True,
            max_length = 100,
            help_text="Nama Kategori")
    slug = AutoSlugField(max_length=100, 
            unique=True, 
            db_index=True,
            populate_from=('name',))
    description = models.TextField(blank=True,
            help_text="Deskripsi Kategori")
    is_archived = models.BooleanField(default = False,
            help_text="Centang untuk Menyembunyikan Kategori") 
    site = models.ForeignKey(Site, on_delete=models.CASCADE,related_name='product_category_site', null=True, blank=True)
   
    class Meta:
        verbose_name_plural = "Categories"

    def get_edit_url(self):
        return "%s" % (reverse('store:category_edit_delete', kwargs={'action':'edit', 'pk':self.pk}))

    def get_delete_url(self):
        return "%s" % (reverse('store:category_edit_delete', kwargs={'action':'delete', 'pk':self.pk}))
   

    def __str__(self):
       return self.name

    def get_url(self):
        return "/store/kategori/%s/" % (self.pk)


class Product(models.Model):
    name = models.CharField(max_length = 200,
            db_index=True,
            help_text="Nama Produk")
    slug = AutoSlugField(max_length=100, 
            db_index=True,
            unique=True, 
            populate_from=('name',))
    description = models.TextField(help_text="Deskripsi Produk")
    photo = models.ImageField(upload_to = 'product_photo',
            help_text="Foto Produk")
    photo_alt1 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 1")
    photo_alt2 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 2")
    photo_alt3 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 3")
    photo_alt4 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 4")
    photo_alt5 = models.ImageField(upload_to = 'product_photo', null=True, blank=True,
            help_text="Foto Produk Alternatif 5")
    price = models.PositiveIntegerField(null=True, help_text="Harga Produk")

    unit_weight = models.PositiveIntegerField(null=True, help_text="Berat Satuan Produk dalam gram")
    is_available = models.BooleanField(default = True,
            help_text="Centang Jika Produk Tersedia")
    is_featured = models.BooleanField(default = False,
            help_text="Centang untuk menjadikan unggulan")
    is_archived = models.BooleanField(default = False,
            help_text="Centang untuk Menyembunyikan Produk")
    categories = models.ManyToManyField(Category, 
            related_name="products_in_category",
            help_text="Kategori Produk")
    site = models.ForeignKey(Site, on_delete=models.CASCADE,related_name='product_site', null=True, blank=True)
    
    def get_details(self):
        details = {'name': self.name,
                   'weight' : self.unit_weight,
                   'price' : self.price}
        return details

    def get_photo_url(self):
        return "/media/%s" % (self.photo)

    def get_photo_alt1_url(self):
        return "/media/%s" % (self.photo_alt1)
    def get_photo_alt2_url(self):
        return "/media/%s" % (self.photo_alt2)
    def get_photo_alt3_url(self):
        return "/media/%s" % (self.photo_alt3)
    def get_photo_alt4_url(self):
        return "/media/%s" % (self.photo_alt4)
    def get_photo_alt5_url(self):
        return "/media/%s" % (self.photo_alt5)

    def get_edit_url(self):
        return "%s" % (reverse('store:product_edit_delete', kwargs={'action':'edit', 'pk':self.pk}))

    def get_delete_url(self):
        return "%s" % (reverse('store:product_edit_delete', kwargs={'action':'delete', 'pk':self.pk}))
    
    def get_detail_url(self):
        return reverse('storefront:product_detail', kwargs={'product_pk':self.pk})

    class Meta:
        verbose_name_plural = "Products"

    def __str__(self):
       return self.name

store/st_purchase_order/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.contrib.auth.models import User
from store.st_shopping_cart.models import Cart
from store.st_catalog.models import Product
from store.st_customer.models import Customer

from membership.models import Member
from django.utils.crypto import get_random_string
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

class PurchaseOrder(models.Model):
    user = models.ForeignKey(User, related_name="users_order", on_delete=models.SET_NULL, null=True)
    total_price = models.PositiveIntegerField(null=True, help_text="Total Belanja")
    discount = models.PositiveIntegerField(null=True, help_text="Diskon Member")
    shipping_cost = models.PositiveIntegerField(null=True, help_text="Ongkos Kirim")
    total_payment = models.PositiveIntegerField(null=True, help_text="Total Belanja")
    created_date = models.DateTimeField(db_index=True,default=datetime.datetime.now)
    payment_date = models.DateTimeField(null=True, db_index=True, blank=True)
    #token_expiry_date = models.DateTimeField(null=True, blank=True)
    #is_tokenized = models.BooleanField(db_index=True,default=False)
    #is_token_expired = models.BooleanField(db_index=True,default=False)
    is_verified = models.BooleanField(db_index=True,default=False)
    is_valid = models.BooleanField(db_index=True,default=True)
    is_paid = models.BooleanField(db_index=True,default=False)
    is_checked_out = models.BooleanField(db_index=True,default=False)
    order_number = models.CharField(db_index=True, max_length=20, blank=True)
    alamat_tujuan = models.CharField(max_length=500, blank=True)
    service = models.CharField(max_length=200, blank=True)
    sub_service = models.CharField(max_length=200, blank=True) #done
    #payment_status = models.TextField(blank=True)
    #payment_token = models.CharField(null=True, max_length=50, blank=True)

    site = models.ForeignKey(Site, on_delete=models.CASCADE,related_name='order_site', null=True, blank=True)
    
    seller = models.ForeignKey(Member, on_delete=models.SET_NULL,related_name='order_seller', null=True, blank=True)
    costumer = models.ForeignKey(Customer, on_delete=models.SET_NULL,related_name='order_customer', null=True, blank=True)

    def get_number():
        order_number_alpha = get_random_string(5, 
            allowed_chars='0123456789')
        order_number_beta = get_random_string(5, 
            allowed_chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ')
        order_number = '%s%s'%(order_number_alpha, order_number_beta)
        if PurchaseOrder.objects.filter(order_number= order_number).exists():
            get_number()
        else:
            return 'INV-{}'.format(order_number)

    def get_detail_url(self):
        return '/str/order/edit/%s/'%(self.pk)

    class Meta:
        ordering = ['-created_date']
        verbose_name = "PurchaseOrder"
        verbose_name_plural = "Purchase Orders"

    def __str__(self):
       return 'Purchase Order No. : %s'%self.order_number

class PurchaseOrderItem(models.Model):
    quantity = models.PositiveIntegerField(null=True, blank=True)
    product = models.ForeignKey(Product, related_name="product_in_order", on_delete=models.SET_NULL, null=True)
    purchase_order = models.ForeignKey(PurchaseOrder, related_name="item_in_order", on_delete=models.SET_NULL, null=True)
    product_referal = models.ForeignKey(Member, on_delete=models.SET_NULL, db_index=True,  related_name="product_order_referal", null=True, blank=True) 
    is_valid = models.BooleanField(db_index=True,default=True)
    
    class Meta:
        verbose_name_plural = "items in Order"

    def get_item_details(self):
        details = {}
        details['product_details'] = Product.get_details(self.product)
        details['total_weight'] = self.quantity * self.product.unit_weight
        details['subtotal'] = self.quantity * self.product.price
        return details

    def __str__(self):
       return 'CartItem%s'%self.pk

@receiver(post_save, sender=PurchaseOrder)
def create_purchase_order(sender, instance, created, **kwargs):
    if created:
        instance.order_number = PurchaseOrder.get_number()
        instance.save()

store/st_purchase_order/forms.py
from django import forms
from .models import PurchaseOrder

class OrderAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderAddForm, self).__init__(*args, **kwargs)
        self.fields['is_verified'].widget.attrs['style'] = 'margin:10px 10px 0 0'
        self.fields['is_verified'].widget.attrs['data-toggle'] = 'toggle'
        self.fields['is_verified'].widget.attrs['data-on'] = 'Yes'
        self.fields['is_verified'].widget.attrs['data-off'] = 'No'
        self.fields['is_verified'].widget.attrs['data-onstyle'] = 'success'
        self.fields['is_verified'].widget.attrs['data-offstyle'] = 'danger'

        self.fields['is_valid'].widget.attrs['style'] = 'margin:10px 10px 0 0'
        self.fields['is_valid'].widget.attrs['data-toggle'] = 'toggle'
        self.fields['is_valid'].widget.attrs['data-on'] = 'Yes'
        self.fields['is_valid'].widget.attrs['data-off'] = 'No'
        self.fields['is_valid'].widget.attrs['data-onstyle'] = 'success'
        self.fields['is_valid'].widget.attrs['data-offstyle'] = 'danger'

        self.fields['is_paid'].widget.attrs['style'] = 'margin:10px 10px 0 0'
        self.fields['is_paid'].widget.attrs['data-toggle'] = 'toggle'
        self.fields['is_paid'].widget.attrs['data-on'] = 'Yes'
        self.fields['is_paid'].widget.attrs['data-off'] = 'No'
        self.fields['is_paid'].widget.attrs['data-onstyle'] = 'success'
        self.fields['is_paid'].widget.attrs['data-offstyle'] = 'danger'

    class Meta:
        model = PurchaseOrder
        fields = ('is_verified',
        'is_valid',
        'is_paid',
        )

store/st_purchase_order/templates/st_purchase_order/component/purchase_order_edit_local_script.html
<script>
    function localScript(){
        $(function() {
            ($('#id_is_verified').bootstrapToggle())();
            ($('#id_is_vaild').bootstrapToggle())();
            ($('#id_is_paid').bootstrapToggle())();
        })
    }

    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
</script>

store/st_purchase_order/templates/st_purchase_order/component/purchase_order_edit_main.html
{% load int_to_rupiah %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/')">Store</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/order/')">Order</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ data.order.order_number }}</li>
        </ol>
    </nav>
{% endblock %}


<div class="row">
    <div class="col-sm-12">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="col-sm-12">
        <form id='addArticleForm' method="POST" enctype="multipart/form-data">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{token}}">
            <div class="row">
                <!-- column -->
                <div class="col-xs-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <h3>Order No. : {{ data.order.order_number }}</h3>
                            <hr>
                            <div class="row">
                                <div class="col-xs-12 col-md-2">
                                    <h4>{{ form.is_paid.label }} <br> {{ form.is_paid }}</h4>
                                    <br>
                                    <h4>{{ form.is_verified.label }} <br> {{ form.is_verified }}</h4>
                                    <br>
                                    <h4>{{ form.is_valid.label }} <br> {{ form.is_valid }}</h4>
                                </div>
                                <div class="col-xs-12 col-md-3">
                                    <h4>Total Price</h4>
                                        
                                        <p>{{ data.order.total_price | int_to_rupiah }}</p>
                                    <h4>Discount</h4>
                                        
                                        <p>{{ data.order.discount | int_to_rupiah }}</p>
                                    <h4>Shipping Cost</h4>
                                        
                                        <p>{{ data.order.shipping_cost | int_to_rupiah }}</p>
                                    <h4>Total Payment</h4>
                                        
                                        <p>{{ data.order.total_payment | int_to_rupiah }}</p>
                                </div>
                                <div class="col-xs-12 col-md-7">
                                    <h4>Customer</h4>
                                        <p>{{ data.order.costumer.username | title }}</p>
                                    <h4>Shipping Address</h4>
                                        <p>{{ data.order.alamat_tujuan | title }}</p> 
                                    <h4>Service</h4>
                                        <p>{{ data.order.service }}</p>
                                    <h4>Sub Service</h4>
                                        <p>{{ data.order.sub_service }}</p>
                                </div>
                                <div class="col-xs-12 col-sm-12">
                                    <hr>
                                    <div class="row" style="margin-bottom:5px">
                                        <div class="col-xs-2 col-sm-1">
                                        </div>
                                        <div class="col-xs-6 col-sm-7">
                                            <p style="font-weight: bold">Product Name</p>
                                        </div>
                                        <div class="col-xs-2 col-sm-2">
                                            <p style="font-weight: bold">Quantity</p>
                                        </div>
                                        <div class="col-xs-2 col-sm-2">
                                            <p style="font-weight: bold">Product Price</p>
                                        </div>
                                        {% if not forloop.last %}
                                        <hr>
                                        {% endif %}
                                    </div>
                                    <hr>
                                        {% for item in data.order.item_in_order.all %}
                                            <div class="row" style="margin-bottom:5px">
                                                <div class="col-xs-2 col-sm-1">
                                                    <img src="{{ item.product.get_photo_url }}" style="width:100%; max-width: 60px; height:auto">
                                                </div>
                                                <div class="col-xs-6 col-sm-7">
                                                    <a href="{{item.product.get_detail_url}}" target="_blank">{{ item.product.name | title }}</a>
                                                </div>
                                                <div class="col-xs-2 col-sm-2">
                                                    {{ item.quantity }}
                                                </div>
                                                <div class="col-xs-2 col-sm-2">
                                                    {{ item.product.price | int_to_rupiah }}
                                                </div>
                                                {% if not forloop.last %}
                                                <div class="col-xs-12 col-sm-12">
                                                <hr>
                                                </div>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    <hr>
                                    <p class="btn btn-primary" style="float:right;margin: auto" onclick="submitNewArticle()">SUBMIT</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

store/st_purchase_order/templates/st_purchase_order/component/purchase_order_local_script.html
<script>
    function localScript(){
    }

    function submitNewArticle(){
        $('#addArticleForm').submit();
    }
    try {
        ($('#id_is_published').bootstrapToggle())();
        ($('#id_is_featured').bootstrapToggle())();
        throw "Exception"; // generates an exception
    }
    catch (e) {}
</script>

store/st_purchase_order/templates/st_purchase_order/component/purchase_order_main.html
{% load humanize int_to_rupiah %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)" onclick="getNext('/str/')">Store</a></li>
            <li class="breadcrumb-item active" aria-current="page">Order</li>
        </ol>
    </nav>
{% endblock %}

<div class="row">
    <!-- column -->
    <div class="col-sm-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="row" style="margin: 0">
                    <div class="col-xs-12 col-sm-12" style="text-align: left">
                        <h3>Order </h3>
                        <p>Total order: {{ site.order_site.all | length }}</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-xs-4 col-sm-2" style="text-align: left">
                        <h6>Order Number</h6>
                    </div>
                    <div class="col-xs-4 col-sm-1" style="text-align: left">
                        <h6>Created Date</h6>
                    </div>
                    <div class="col-xs-4 col-sm-1" style="text-align: left">
                        <h6>Payment Date</h6>
                    </div>
                    <div class="col-xs-4 col-sm-1" style="text-align: left">
                        <h6>Customer</h6>
                    </div>
                    <div class="col-xs-2 col-sm-1" style="text-align: center">
                        <h6>Is Valid</h6>
                    </div>
                    <div class="col-xs-2 col-sm-1" style="text-align: center">
                        <h6>Is Paid</h6>
                    </div>
                    <div class="col-xs-2 col-sm-1" style="text-align: center">
                        <h6>Is Verified</h6>
                    </div>
                    <div class="col-xs-4 col-sm-4" style="text-align: left">
                        <h6>Total Payment </h6>
                    </div>
                </div>
                <hr>
                {% for order in site.order_site.all %}
                    <div class="row" style="margin: 0">
                        <div class="col-xs-4 col-sm-2" style="text-align: left">
                            <h6><a href="javascript:void(0)" onclick="window.open('{{order.get_detail_url}}', '_parent')">{{order.order_number}}</a></h6>
                        </div>
                        <div class="col-xs-4 col-sm-1" style="text-align: left">
                            <h6>{{order.created_date|date:"j/n/Y"}}</h6>
                        </div>
                        <div class="col-xs-4 col-sm-1" style="text-align: left">
                            <h6>{{order.payment_date|date:"j/n/Y"}}</h6>
                        </div>
                        <div class="col-xs-4 col-sm-1" style="text-align: left">
                            <h6>{{order.costumer.username | title}}</h6>
                        </div>
                        <div class="col-xs-2 col-sm-1" style="text-align: center">
                            {% if order.is_valid %}
                            <span class="text-success fa fa-check"></span>
                            {% else %}
                            <span class="text-danger fa fa-times"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-2 col-sm-1" style="text-align: center">
                            {% if order.is_paid %}
                            <span class="text-success fa fa-check"></span>
                            {% else %}
                            <span class="text-danger fa fa-times"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-2 col-sm-1" style="text-align: center">
                            {% if order.is_verified %}
                            <span class="text-success fa fa-check"></span>
                            {% else %}
                            <span class="text-danger fa fa-times"></span>
                            {% endif %}
                        </div>
                        <div class="col-xs-4 col-sm-4" style="text-align: left">
                            <h6>{{order.total_payment | int_to_rupiah}} </h6>
                        </div>
                    </div>
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- column -->
</div>